name: masters-thesis-eval
channels:
  - nvidia
dependencies:
  - python=3.6
  - cudatoolkit=11.0
  - cudnn=8
  - cython
  - libopenblas
  - py-opencv
  - scipy
  - tqdm
  - pyyaml
  - pip
  - pip:
      - --find-links https://download.pytorch.org/whl/lts/1.8/torch_lts.html
      - torch==1.8.2+cpu
      - torchvision==0.9.2+cpu
      - torchaudio==0.8.2
      - basicsr==1.3.4.2
      - bm3d==3.0.9
      - jupyter
      - flake8
      - black
      - pandas==1.1.5
      - seaborn==0.11.1
      - imageio
      - sklearn
      - tensorflow==2.4.3
      - tensorflow-addons==0.12
      - tensorflow-probability==0.12.2
      - tensorflow-datasets
      - image_similarity_measures
      - git+https://github.com/HedgehogCode/tensorflow-datasets-bw.git@0.11.1
      - git+https://github.com/HedgehogCode/pyinverseflow@0.1.0
      - git+https://github.com/HedgehogCode/deep-plug-and-play-prior@thesis
      - git+https://github.com/pathak22/pyflow
